import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, roc_curve, auc, classification_report
from fpdf import FPDF

# ==========================================
# 0. PDF 生成函式 (安全英文版)
# ==========================================
def create_pdf(user_name, risk_type, prob, factors):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Alzheimer's Risk Assessment Report", ln=1, align='C')
    pdf.ln(10)
    
    tw_time = pd.Timestamp.now() + pd.Timedelta(hours=8)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"User ID: {user_name}", ln=1)
    pdf.cell(200, 10, txt=f"Date: {tw_time.strftime('%Y-%m-%d %H:%M')}", ln=1)
    pdf.ln(5)
    
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt=f"Risk Level: {risk_type}", ln=1)
    pdf.cell(200, 10, txt=f"Probability: {prob:.1%}", ln=1)
    pdf.ln(5)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Key Risk Factors:", ln=1)
    pdf.set_font("Arial", size=11)
    for key, value in factors.items():
        pdf.cell(200, 8, txt=f"- {str(key)}: {str(value)}", ln=1)
    pdf.ln(10)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Medical Advice:", ln=1)
    pdf.set_font("Arial", size=11)
    
    if risk_type == "High":
        advice_text = "High risk detected. Immediate clinical consultation with a neurologist is recommended."
    elif risk_type == "Moderate":
        advice_text = "Moderate risk detected. Please improve sleep quality, maintain a healthy diet, and monitor regularly."
    else:
        advice_text = "Low risk detected. Continue maintaining a healthy lifestyle and regular exercise."
    
    pdf.multi_cell(0, 8, txt=advice_text)
    
    # 加入免責聲明到 PDF 底部
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 5, txt="Disclaimer: This report is generated by an AI prototype using synthetic and historical data. It is for academic research purposes only and does not constitute a medical diagnosis.")
    
    return pdf.output(dest='S').encode('latin-1')

# ==========================================
# 1. 頁面配置 & 清爽藍白 UI
# ==========================================
st.set_page_config(page_title="AD Risk AI Pro", page_icon="🧠", layout="wide")

st.markdown("""
    <style>
    .main {background-color: #FFFFFF;}
    h1, h2, h3 {color: #0056b3; font-family: 'Helvetica Neue', sans-serif;}
    .stButton>button {
        color: white; background: linear-gradient(135deg, #007bff 0%, #0056b3 100%);
        border: none; border-radius: 8px; padding: 12px 24px; width: 100%; font-weight: bold;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1); transition: 0.2s;
    }
    .stButton>button:hover {transform: translateY(-2px); box-shadow: 0 4px 8px rgba(0,0,0,0.2);}
    [data-testid="stSidebar"] {background-color: #F0F4F8; border-right: 1px solid #D1D9E6;}
    .stChatMessage {background-color: #F8F9FA; border: 1px solid #E9ECEF; border-radius: 12px; padding: 15px; margin-bottom: 10px;}
    [data-testid="stSidebar"] img {display: block; margin-left: auto; margin-right: auto; border-radius: 50%; border: 3px solid #007bff;}
    
    /* 解釋區塊樣式 */
    .explanation-box {
        background-color: #e8f4fd; 
        border-left: 5px solid #007bff; 
        padding: 15px; 
        border-radius: 5px;
        margin-top: 10px;
        font-size: 0.95em;
        color: #2c3e50;
    }
    
    /* 免責聲明區塊 */
    .disclaimer-box {
        background-color: #fff3cd;
        border: 1px solid #ffeeba;
        color: #856404;
        padding: 10px;
        border-radius: 5px;
        font-size: 0.85em;
        margin-top: 20px;
    }
    </style>
    """, unsafe_allow_html=True)

# ==========================================
# 2. 資料載入與模型訓練
# ==========================================
@st.cache_resource
def load_all():
    # 生活模型
    df_l = pd.read_csv('alzheimers_disease_data.csv')
    feat_l = ['Age', 'BMI', 'SleepQuality', 'PhysicalActivity', 'DietQuality', 'FamilyHistoryAlzheimers', 'SystolicBP', 'FunctionalAssessment', 'ADL']
    X_l = df_l[feat_l]; y_l = df_l['Diagnosis']
    X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(X_l, y_l, test_size=0.2, random_state=42)
    clf_l = RandomForestClassifier(n_estimators=100, random_state=42).fit(X_train_l, y_train_l)
    
    # 臨床模型
    df_c_raw = pd.read_csv('oasis_cross-sectional.csv').rename(columns={'Educ': 'EDUC'})
    df_long_raw = pd.read_csv('oasis_longitudinal.csv')
    df_long_raw = df_long_raw[df_long_raw['Visit'] == 1]
    common = ['M/F', 'Age', 'EDUC', 'SES', 'MMSE', 'CDR', 'eTIV', 'nWBV']
    df_oasis = pd.concat([df_c_raw[[c for c in common if c in df_c_raw.columns]], 
                         df_long_raw[[c for c in common if c in df_long_raw.columns]]], ignore_index=True).dropna()
    df_oasis['M/F'] = df_oasis['M/F'].apply(lambda x: 1 if str(x).startswith('F') else 0)
    df_oasis['Target'] = df_oasis['CDR'].apply(lambda x: 1 if x > 0 else 0)
    feat_c = ['M/F', 'Age', 'EDUC', 'SES', 'eTIV', 'nWBV']
    X_c = df_oasis[feat_c]; y_c = df_oasis['Target']
    X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_c, y_c, test_size=0.2, random_state=42)
    clf_c = RandomForestClassifier(n_estimators=100, random_state=42).fit(X_train_c, y_train_c)
    
    return clf_l, (X_test_l, y_test_l), clf_c, (X_test_c, y_test_c), df_oasis, df_l

model_l, test_l, model_c, test_c, df_oasis, df_life_raw = load_all()

# ==========================================
# 3. 側邊欄
# ==========================================
try: st.sidebar.image("brain_compare.png", width=150)
except: st.sidebar.image("https://cdn-icons-png.flaticon.com/512/3063/3063176.png", width=150)

st.sidebar.markdown("<h2 style='text-align: center; color: #0056b3;'>AD-AI Pro v6.3</h2>", unsafe_allow_html=True)
st.sidebar.markdown("---")
app_mode = st.sidebar.radio("功能導航", ["🏠 系統首頁", "🤖 AI 衛教諮詢", "🥗 生活雷達篩檢", "🏥 臨床落點分析", "📊 數據驗證中心"])
st.sidebar.markdown("---")

# [新增] 側邊欄免責聲明
with st.sidebar.expander("⚠️ 免責聲明 (Disclaimer)"):
    st.markdown("""
    本系統為學術專題研究原型 (Prototype)。
    - **生活數據**：使用 Kaggle 合成數據集，僅供模型驗證。
    - **臨床數據**：使用 OASIS 公開數據集。
    - **結果用途**：僅供教學與研究參考，**非醫療診斷依據**。若有健康疑慮，請務必諮詢專業醫師。
    """)

st.sidebar.caption("Designed by NYCU MED Project Team")

# ==========================================
# 4. 頁面邏輯
# ==========================================

# --- PAGE 1: 首頁 ---
if app_mode == "🏠 系統首頁":
    st.title("🧠 阿茲海默症雙軌風險評估系統")
    st.markdown("#### Dual-Track Alzheimer's Risk Assessment System")
    st.divider()
    
    col1, col2 = st.columns([1, 1])
    with col1:
        st.info("👋 **歡迎使用 v6.3 專業版！**")
        st.markdown("""
        **系統關鍵字導覽：**
        - **🔍 網站操作**：點擊左上角「>」展開側邊欄選單切換功能。
        - **🤖 功能介紹**：包含 AI 問答、生活習慣分析、MRI 影像判讀。
        - **📄 報告生成**：支援一鍵下載 PDF 醫師參考報告。
        
        **五大核心模組：**
        1. **🤖 AI 諮詢**：提供就醫指引、費用諮詢與衛教問答。
        2. **🥗 生活雷達**：五維度分析（睡眠/飲食/運動/記憶/自理）。
        3. **🏥 臨床落點**：nWBV 腦萎縮程度定位與基因加權。
        4. **📊 數據實證**：ROC 曲線與模型效能驗證。
        """)
        
        # [新增] 首頁免責聲明區塊
        st.markdown("""
        <div class="disclaimer-box">
        ⚠️ <b>注意：數據限制與免責聲明</b><br>
        本系統之「生活型態數據」採用合成資料集進行模型訓練，「臨床數據」則基於 OASIS 歷史資料。ApoE4 基因分析功能目前為模擬加權，尚未串接真實基因庫。分析結果僅供學術研究參考。
        </div>
        """, unsafe_allow_html=True)

    with col2:
        try: st.image("brain_compare.png", use_container_width=True, caption="Healthy Brain (Left) vs AD Brain (Right)")
        except: st.warning("請確保 brain_compare.png 已上傳")

# --- PAGE 2: AI Chatbot ---
elif app_mode == "🤖 AI 衛教諮詢":
    st.title("🤖 AI 衛教諮詢助手")
    st.info("💡 提示：您可以問我關於「阿茲海默症」的相關問題，例如症狀、預防、治療、就醫資訊或網站操作方法。")
    
    if "messages" not in st.session_state:
        st.session_state.messages = [{"role": "assistant", "content": "您好！我是您的健康管家。請問今天有什麼我可以幫您的嗎？"}]

    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    if prompt := st.chat_input("請輸入您的問題..."):
        st.chat_message("user").markdown(prompt)
        st.session_state.messages.append({"role": "user", "content": prompt})

        q = prompt.lower()
        if any(x in q for x in ["操作", "怎麼用", "功能", "教學"]):
            reply = "🛠️ **網站操作指南**：\n請點擊左上角的 **「>」符號** 展開側邊欄選單，您會看到以下功能：\n1. **生活雷達篩檢**：輸入您的日常習慣，評估風險。\n2. **臨床落點分析**：輸入 MRI 數據，查看腦部健康落點。\n3. **數據驗證中心**：查看本系統的準確度數據。"
        elif any(x in q for x in ["阿茲海默", "失智", "老人痴呆", "什麼是"]):
            reply = "🧠 **疾病簡介**：\n阿茲海默症 (Alzheimer's Disease) 是一種不可逆的大腦神經退化疾病。主要病理特徵為大腦內 **β-類澱粉蛋白斑塊** 堆積與 **Tau 蛋白纏結**，導致神經元死亡與腦部萎縮 (Brain Atrophy)。"
        elif any(x in q for x in ["飲食", "吃", "營養", "食物"]):
            reply = "🥗 **飲食建議 (MIND Diet)**：\n研究證實 MIND 飲食可降低失智風險。建議多攝取：\n- **綠色蔬菜**、**堅果**、**莓果類**、**全穀類**、**魚類**。\n- 應避免：紅肉、奶油、起司、甜點、油炸食品。"
        elif any(x in q for x in ["運動", "跑步", "活動"]):
            reply = "🏃 **運動處方**：\n建議每週至少 150 分鐘中等強度有氧運動。運動能促進 **BDNF (腦源性神經滋養因子)** 分泌，增加海馬迴體積，增強記憶力。"
        elif any(x in q for x in ["睡眠", "睡覺", "失眠"]):
            reply = "😴 **睡眠與大腦排毒**：\n大腦在睡眠時會啟動 **「膠淋巴系統 (Glymphatic System)」** 清除代謝廢物。長期睡眠不足會導致毒素堆積，增加失智風險。建議每晚睡滿 7-8 小時。"
        elif any(x in q for x in ["診所", "掛號", "看醫生", "醫院", "科別"]):
            reply = "🏥 **就醫指引**：\n建議掛 **「神經內科」** 或 **「身心科」**。各大醫學中心皆設有「記憶門診」，可提供認知測驗 (MMSE) 與腦部影像檢查 (MRI)。"
        elif any(x in q for x in ["費用", "錢", "健保", "自費"]):
            reply = "💰 **費用資訊**：\n健保給付大部分的門診與基本檢查。高階自費項目如 **類澱粉蛋白 PET 掃描** 可能需數萬元，建議諮詢主治醫師。"
        elif any(x in q for x in ["你好", "嗨", "早安", "謝謝"]):
            reply = "😊 您好！很高興能為您服務。若有任何關於大腦健康的問題，歡迎隨時提問！"
        else:
            reply = "抱歉，我的資料庫目前僅涵蓋「疾病介紹、飲食、運動、睡眠、就醫、費用、網站操作」等主題。您可以試著問：「這個網站怎麼用？」或「要去哪裡看醫生？」"

        with st.chat_message("assistant"):
            st.markdown(reply)
        st.session_state.messages.append({"role": "assistant", "content": reply})

# --- PAGE 3: 生活篩檢 ---
elif app_mode == "🥗 生活雷達篩檢":
    st.title("🥗 生活型態風險評估")
    st.markdown("輸入您的生活習慣，系統將生成雷達圖，並將您的數據與資料庫常模進行比較。")
    st.divider()
    
    c1, c2 = st.columns([1, 2])
    with c1:
        st.subheader("📝 輸入資料")
        l_age = st.slider("年齡", 40, 95, 65); l_gen = st.selectbox("性別", ["男", "女"])
        l_bmi = st.slider("BMI (身體質量指數)", 15.0, 35.0, 24.0) 
        l_fam = st.radio("家族病史", ["無", "有"])
        l_sleep = st.slider("睡眠品質 (0-10)", 0, 10, 7); l_diet = st.slider("飲食品質 (0-10)", 0, 10, 7)
        l_act = st.slider("運動頻率 (0-10)", 0, 10, 5); l_func = st.slider("記憶自評 (0-10)", 0.0, 10.0, 8.0)
        l_adl = st.slider("自理能力 (0-10)", 0.0, 10.0, 10.0)
        btn_run = st.button("生成深度分析報告")

    if btn_run:
        input_data = [[max(60, l_age), l_bmi, l_sleep, l_act, l_diet, (1 if l_fam=="有" else 0), 120, l_func, l_adl]]
        prob = model_l.predict_proba(input_data)[0][1]
        if l_fam == "有": prob = min(0.99, prob * 1.3)
        if l_gen == "女": prob = min(0.99, prob * 1.1)
        if l_age < 60: prob *= 0.7
        
        with c2:
            st.subheader("📊 分析結果與圖表解讀")
            
            # 1. 雷達圖
            cat = ['Sleep', 'Diet', 'Exercise', 'Memory', 'ADL']
            vals = [l_sleep/10, l_diet/10, l_act/10, l_func/10, l_adl/10]
            vals += vals[:1]; ang = np.linspace(0, 2*np.pi, 5, endpoint=False).tolist(); ang += ang[:1]
            fig, ax = plt.subplots(figsize=(4, 4), subplot_kw=dict(polar=True))
            ax.fill(ang, vals, color='#007bff', alpha=0.3); ax.plot(ang, vals, color='#0056b3')
            ax.set_xticks(ang[:-1]); ax.set_xticklabels(cat); st.pyplot(fig)
            
            st.markdown("""
            <div class="explanation-box">
            <b>圖表解讀：</b><br>
            這張雷達圖顯示了您的五大健康維度。<b>面積越大代表越健康</b>。<br>
            若某個角向內凹陷（例如 Sleep < 5），代表該項目是您的弱點，建議優先改善。
            </div>
            """, unsafe_allow_html=True)
            
            # 2. 群體比較圖 (BMI)
            st.markdown("#### ⚖️ 您的 BMI 落點分析")
            fig2, ax2 = plt.subplots(figsize=(6, 2))
            sns.histplot(data=df_life_raw, x='BMI', kde=True, color='gray', alpha=0.3, ax=ax2)
            ax2.axvline(x=l_bmi, color='red', linestyle='--', linewidth=3, label='You')
            ax2.legend()
            ax2.set_title("Population BMI Distribution")
            st.pyplot(fig2)
            
            st.markdown("""
            <div class="explanation-box">
            <b>BMI 分析：</b><br>
            紅色虛線代表您的 BMI。灰色區域是 2,000 位受試者的分佈。<br>
            - 若落在右側 (BMI > 30)，代表體重偏高，可能增加心血管與失智風險。<br>
            - 若落在中間 (BMI 18.5-24)，屬於健康範圍。
            </div>
            """, unsafe_allow_html=True)

            # 3. 風險評估
            risk_lvl = "High" if prob > 0.6 else ("Moderate" if prob > 0.3 else "Low")
            st.metric("預測風險機率", f"{prob:.1%}", delta="High Risk" if risk_lvl=="High" else "Low Risk", delta_color="inverse")
            
            fam_eng = "Yes" if l_fam == "有" else "No"
            pdf_bytes = create_pdf(f"User_{l_age}", risk_type=risk_lvl, prob=prob, factors={"BMI": l_bmi, "Sleep": l_sleep, "Activity": l_act, "Family History": fam_eng})
            st.download_button("📥 下載 PDF 評估報告", data=pdf_bytes, file_name="AD_Risk_Report.pdf", mime="application/pdf")

# --- PAGE 4: 臨床落點 (新增ApoE4模擬提示) ---
elif app_mode == "🏥 臨床落點分析":
    st.title("🏥 臨床影像定位分析")
    st.markdown("輸入 MRI 影像數值，分析您在同齡族群中的腦萎縮程度落點。")
    st.divider()
    
    c1, c2 = st.columns([1, 2])
    with c1:
        st.subheader("🧠 影像數據")
        c_age = st.number_input("年齡", 60, 95, 75); c_gen = st.selectbox("性別", ["Male", "Female"]) 
        c_ses = st.selectbox("社經地位 (SES)", [1,2,3,4,5], index=1)
        c_educ = st.number_input("教育年數", 0, 25, 12); c_nwbv = st.slider("nWBV (腦體積比)", 0.65, 0.85, 0.75, 0.001)
        c_etiv = st.number_input("eTIV (顱內容量)", 1100, 2000, 1450)
        
        # [修改] 標註模擬情境
        c_apoe = st.selectbox("ApoE4 基因型 (模擬情境)", ["Negative", "Positive (e3/e4)", "High Risk (e4/e4)"], 
                              help="本選項僅用於模擬基因風險對預測機率的影響，不代表真實基因檢測結果。")
        
        btn_c = st.button("執行臨床落點分析")

    if btn_c:
        g_val = 1 if c_gen == "Female" else 0
        input_c = [[g_val, c_age, c_educ, c_ses, c_etiv, c_nwbv]]
        prob_c = model_c.predict_proba(input_c)[0][1]
        if "High" in c_apoe: prob_c = min(0.99, prob_c * 1.5)
        elif "Positive" in c_apoe: prob_c = min(0.99, prob_c * 1.2)
        
        with c2:
            st.subheader("📍 落點視覺化 (You are Here)")
            fig, ax = plt.subplots(figsize=(8, 5))
            sns.scatterplot(data=df_oasis, x='Age', y='nWBV', hue='CDR', palette='coolwarm', alpha=0.3, ax=ax)
            ax.scatter(c_age, c_nwbv, color='red', s=250, marker='*', label='You Are Here', edgecolors='black')
            ax.set_ylabel("nWBV (Normalized Whole Brain Volume)")
            ax.legend(); st.pyplot(fig)
            
            st.markdown("""
            <div class="explanation-box">
            <b>圖表解讀：</b><br>
            <ul>
            <li><b>X軸 (Age)</b>：年齡。</li>
            <li><b>Y軸 (nWBV)</b>：全腦體積比，數值越低代表腦萎縮越嚴重。</li>
            <li><b>背景點</b>：藍色代表健康者，紅色代表失智患者。</li>
            <li><b>紅星 (You Are Here)</b>：您的位置。若落入右下角紅點區，代表在同年齡層中，您的腦萎縮較嚴重，風險較高。</li>
            </ul>
            </div>
            """, unsafe_allow_html=True)
            
            st.metric("影像分析風險機率", f"{prob_c:.1%}")
            if prob_c > 0.5: st.error("🔴 高度疑似阿茲海默症病變 (腦萎縮顯著)")
            else: st.success("🟢 目前無明顯阿茲海默症特徵 (腦容量正常)")

# --- PAGE 5: 數據驗證 ---
elif app_mode == "📊 數據驗證中心":
    st.title("📊 數據驗證中心 (Data Validation)")
    st.markdown("#### Model Performance & Static Analysis")
    st.info("本區展示模型的準確度驗證 (ROC Curve) 與訓練數據的靜態分析圖表，證明系統的醫學可信度。")
    st.divider()
    
    tab1, tab2, tab3 = st.tabs(["生活模型效能 (ROC)", "臨床模型效能 (ROC)", "💾 靜態圖表回顧"])
    with tab1:
        st.markdown("**ROC 曲線 (Receiver Operating Characteristic)**：衡量二元分類模型的效能。AUC 越接近 1.0 代表準確度越高。")
        X_t, y_t = test_l; y_p = model_l.predict_proba(X_t)[:, 1]
        fpr, tpr, _ = roc_curve(y_t, y_p); fig, ax = plt.subplots(figsize=(6,4))
        ax.plot(fpr, tpr, label=f'AUC={auc(fpr, tpr):.2f}', color='#007bff', lw=2)
        ax.plot([0,1],[0,1],'k--'); ax.legend(); st.pyplot(fig)
    with tab2:
        st.markdown("**ROC 曲線**：此臨床模型基於 OASIS MRI 數據訓練，具備極高的分辨能力 (AUC通常 > 0.8)。")
        X_t, y_t = test_c; y_p = model_c.predict_proba(X_t)[:, 1]
        fpr, tpr, _ = roc_curve(y_t, y_p); fig, ax = plt.subplots(figsize=(6,4))
        ax.plot(fpr, tpr, label=f'AUC={auc(fpr, tpr):.2f}', color='#28a745', lw=2)
        ax.plot([0,1],[0,1],'k--'); ax.legend(); st.pyplot(fig)
    with tab3:
        st.subheader("OASIS 臨床數據解析")
        c1, c2, c3 = st.columns(3)
        with c1: 
            st.image("scatter_CDR_color.png", use_container_width=True)
            st.caption("▲ **年齡 vs MMSE**：顯示隨著年齡增長，認知分數 (MMSE) 下降的趨勢，紅點代表失智患者集中區。")
        with c2: 
            st.image("heatmap_new.png", use_container_width=True)
            st.caption("▲ **相關性熱圖**：顏色越紅/藍代表相關性越強。可見 nWBV 與 CDR (失智等級) 呈顯著負相關。")
        with c3: 
            st.image("feature_importance_new.png", use_container_width=True)
            st.caption("▲ **特徵重要性**：顯示 nWBV (腦容量) 是預測模型中權重最高的因子，其次是認知測驗分數。")
        
        st.divider()
        st.subheader("Kaggle 生活數據解析")
        c4, c5, c6 = st.columns(3)
        with c4: 
            st.image("csv3_scatter.png", use_container_width=True)
            st.caption("▲ **生活散佈圖**：展示不同生活習慣分群下的健康狀態分佈。")
        with c5: 
            st.image("csv3_heatmap.png", use_container_width=True)
            st.caption("▲ **風險因子熱圖**：分析睡眠、飲食、運動等因子之間的關聯性。")
        with c6: 
            st.image("csv3_bar.png", use_container_width=True)
            st.caption("▲ **生活因子權重**：顯示「功能性評估 (Functional Assessment)」與「ADL」對預測結果影響最大。")
